### PR TITLE
Create kobkob-2018.json

### PR DESCRIPTION
**Pull request by kobkob2018**

### CODE REVIEW

**Comment by szabgab** [comment]
The filename should be exactly the same as your userame

**Comment by szabgab** [comment]
Please change the name of the file.

**Comment by kobkob2018** [comment]
Ok. I have changed the filename to be exactly as my username(hopefully with no mistakes...)

**Comment by szabgab** [comment]
The filename seems to be correct, but now the value of the github field inside is not correct.

**Comment by szabgab** [comment]
now it looks good.

**Comment by szabgab** [comment]
See it on the web site: https://code-maven.github.io/osdc-2023-01-public/

**Pull request merged**
