### PR TITLE
added link to my blogpost at wordpress

### PR DESCRIPTION
**Pull request by ilayni**

### CODE REVIEW

**Comment by szabgab** [comment]
I implemented date fetching on dev.to but not in general so. we now require a field `"published_at"` with a value that looks like this `"2023-01-10T16:29:48Z"` for posts that are not on dev.to

**Comment by szabgab** [comment]
In any case, the linked page only says "coming soon", right?

**Comment by ilayni** [comment]
Hi just saw your comment
where should i put
"published_at" with a value that looks like this "2023-01-10T16:29:48Z"

**Comment by ilayni** [comment]
can you specify the html code for 
"published_at" with a value that looks like this "2023-01-10T16:29:48Z"

**Comment by ilayni** [comment]
didnt seem to update it this is what i see in the htmo source
<meta property="article:published_time" content="2023-01-10T06:22:03+00:00" />

**Comment by ilayni** [comment]
the page doesn't say coming soon
this is the content:
https://cool8200.wordpress.com/2023/01/10/open-source/

**Comment by ilayni** [comment]
no its another content
https://cool8200.wordpress.com/2023/01/10/open-source/

**Comment by szabgab** [comment]
> Hi just saw your comment where should i put "published_at" with a value that looks like this "2023-01-10T16:29:48Z"

I added an example here:  https://github.com/Code-Maven/osdc-2023-01-public/blob/main/mentors/szabgab.json

**Comment by szabgab** [comment]
> the page doesn't say coming soon this is the content: https://cool8200.wordpress.com/2023/01/10/open-source/

to me it still shows a blue page with the text "coming soon" Try to visit it from another browser or a tab in your browser where you are not logged in. Maybe you can see different content as you are logged in?

**Comment by szabgab** [comment]
That's now a link to the whole blog, not a specific entry. A good link would be: https://cool8200.wordpress.com/2023/01/10/open-source/     but that post only has a sentence. I was expecting for more details.

**Pull request merged**
