### PR TITLE
adding posts to json file

### PR DESCRIPTION
**Pull request by zero-pytagoras**
@szabgab

### CODE REVIEW

**Comment by zero-pytagoras** [comment]
@szabgab  at your time.

**Comment by szabgab** [comment]
In the posts list now each entry needs to have a `url` and a `title` key. I just added the test-case. Please update the json file accordingly.

**Comment by zero-pytagoras** [comment]
@szabgab  awaiting for you

**Comment by szabgab** [comment]
thanks

**Comment by szabgab** [comment]
btw there is no need to mention me when you create a new commit as I get notified anyway.

**Pull request merged**
