### PR TITLE
removed special case added for me and updated regex to receive .

### PR DESCRIPTION
**Pull request by anatlavitzkovitz**

### CODE REVIEW

**Comment by szabgab** [comment]
2 comments:
1. No need to escape the dot with the back-slash inside the character class.
2. It would much better - also as practice, to close this PR and go back to the branch you used for the previous PR and make the extra change there. That way we would only have one PR and it would include the discussion we had.

**Comment by anatlavitzkovitz** [comment]
Shuly says you are wrong about 1 because without the back-slash it will receive all the characters.

**Comment by szabgab** [comment]
I'd recommend you check what happens if you put an un-escaped . in a character class. What does that match,

**Comment by szabgab** [comment]
thanks

**Pull request merged**
