### PR TITLE
adding my json

### PR DESCRIPTION
**Pull request by zero-pytagoras**

### CODE REVIEW

**Comment by szabgab** [comment]
you are not supposed to change the `cm-demo.json` file. You are supposed to create your own file with the same name as your username.

**Comment by zero-pytagoras** [comment]
@szabgab  please check

**Comment by szabgab** [comment]
now the file looks good, but as I can see the `cm-demo.json` file is still being removed.
If you click on the "Files changed" on this page you can see that it is removed.

Please restore it.

**Comment by zero-pytagoras** [comment]
@szabgab  at your free time

**Comment by szabgab** [comment]
Apparently there is still a small difference - with or without trailing newline. In a real project probably it would not be accepted as it is unclear why was that change, but for this project it does not ...  I see you fixed it in the meantime. Nice.

**Comment by szabgab** [comment]
and I clicked the wrong button closing the PR instead of merging it. So I had to reopen it and now it is is merged. In a few seconds you'll see it on our website.

**Pull request merged**
